### ISSUE TITLE
MDV Support with 210404

### ISSUE THREAD

**Issue by zompiexx** [MiSTer-devel/QL_MiSTer#3]
Hi,

First of all - thanks for providing such a great QL core.

Up until recently my MDV were working fine, but since upgrading to core version 210404 (maybe before that but I didn't notice), I am unable to access MDV when .WIN is configured.

Is there something else I need to configure?

Best regards,

Andy

**Comment by sorgelig** [comment]
probably @MarcelKilgus can tell

**Comment by MarcelKilgus** [comment]
Still works fine for me.

What OS/QL-SD driver? Does it work without a .WIN mounted? Does is start working after issuing a "WIN_USE" call in Basic?

**Comment by zompiexx** [comment]
Please go ahead and close this issue. I still have issues with some MDV issues, but can work around it.

Thanks,

Andy
