### ISSUE TITLE
FLP support

### ISSUE THREAD

**Issue by zompiexx** [MiSTer-devel/QL_MiSTer#4]
Hi,

Would it be possible to add FLP support to the core?

This would make it so much easier to run commercial available software (e.g. games packs) - which is often supplied as FLP images, without the need to break the files up across multiple MDV images using a software emulator.

Thanks in advance,

Andy

**Comment by MarcelKilgus** [comment]
Unlike other retro-platforms I don't see FLP images to be a thing at all when it comes to the QL. Where do you find them?

No need for multiple MDV images, the suggested way is to use .WIN container.

**Comment by zompiexx** [comment]
Thanks for the quick response. The Games Packs from http://www.rwapsoftware.co.uk/ are distributed as .IMG files which are FLP format. If I am going to  use a software emulator to copy from FLP, MDV or other formats to a .WIN container, then supporting formats other than .WIN on the MiSTer QL core is moot (although would be nice to have for convenience).
